# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-04 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('studentid', models.CharField(max_length=80)),
                ('classname', models.CharField(max_length=80)),
            ],
        ),
    ]
